/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JCheckbox;

import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class EjJCheckbox extends javax.swing.JFrame {

    /**
     * Creates new form EjJCheckbox
     */
    public EjJCheckbox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        panVacinas = new javax.swing.JPanel();
        chkTetano = new javax.swing.JCheckBox();
        chkHepatite = new javax.swing.JCheckBox();
        chkSarampelo = new javax.swing.JCheckBox();
        btnGardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNome.setText("Nome");

        panVacinas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Vacinas Aplicadas"));

        chkTetano.setText("Tetano");

        chkHepatite.setText("Hepatite");

        chkSarampelo.setText("Sarampelo");

        javax.swing.GroupLayout panVacinasLayout = new javax.swing.GroupLayout(panVacinas);
        panVacinas.setLayout(panVacinasLayout);
        panVacinasLayout.setHorizontalGroup(
            panVacinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panVacinasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkTetano)
                .addGap(18, 18, 18)
                .addComponent(chkHepatite)
                .addGap(18, 18, 18)
                .addComponent(chkSarampelo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panVacinasLayout.setVerticalGroup(
            panVacinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panVacinasLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panVacinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkHepatite)
                    .addComponent(chkTetano)
                    .addComponent(chkSarampelo))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        btnGardar.setText("Gardar");
        btnGardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGardar)
                .addGap(152, 152, 152))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panVacinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addGap(37, 37, 37)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(panVacinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGardar)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGardarActionPerformed
        // TODO add your handling code here:
        String nome = txtNome.getText().trim();
        if (nome.compareTo("") == 0) {
            JOptionPane.showMessageDialog(this, "Debe indicar o nome");
            return;
        }
        //Nova Vacinacion
        Vacinacion vacinacion = new Vacinacion(nome);

        //Recollida de datos dos JCheckBoxes
        vacinacion.setTetano(chkTetano.isSelected());
        vacinacion.setHepatite(chkHepatite.isSelected());
        vacinacion.setSarampelo(chkSarampelo.isSelected());

        //Insertar o obxeto creado na BD
        //Non é parte desta unidade didactica
        JOptionPane.showMessageDialog(this, "Rexistro gardado correctamente");
    }//GEN-LAST:event_btnGardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EjJCheckbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EjJCheckbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EjJCheckbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EjJCheckbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EjJCheckbox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGardar;
    private javax.swing.JCheckBox chkHepatite;
    private javax.swing.JCheckBox chkSarampelo;
    private javax.swing.JCheckBox chkTetano;
    private javax.swing.JLabel lblNome;
    private javax.swing.JPanel panVacinas;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
