/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JTextField;

import java.awt.event.KeyEvent;

/**
 *
 * @author usuario
 */
public class EjJTextField extends javax.swing.JFrame {

    /**
     * Creates new form EjJTextField
     */
    public EjJTextField() {
        initComponents();
        txtIdade.setDocument(new LimiteLonxitudeJTextField(3));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        lblIdade = new javax.swing.JLabel();
        lblTel = new javax.swing.JLabel();
        lblRes = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtIdade = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        txtRes = new javax.swing.JTextField();
        btnGardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNome.setText("Nome");

        lblIdade.setText("Idade");

        lblTel.setText("Telefono");

        lblRes.setText("Resultado");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeKeyTyped(evt);
            }
        });

        txtRes.setEditable(false);
        txtRes.setBackground(new java.awt.Color(204, 204, 0));
        txtRes.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnGardar.setText("Gardar");
        btnGardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRes)
                    .addComponent(lblTel)
                    .addComponent(lblIdade)
                    .addComponent(lblNome))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(txtIdade)
                    .addComponent(txtTel)
                    .addComponent(txtRes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGardar)
                .addGap(7, 7, 7))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGardar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdade)
                    .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTel)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRes)
                    .addComponent(txtRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGardarActionPerformed
        // TODO add your handling code here:
        String nome = txtNome.getText().trim();
        String idade = txtIdade.getText().trim();
        String telefono = txtTel.getText().trim();

        if (nome.compareTo("") == 0) {
            txtRes.setText("Debe indicar o nome");
            return;
        }

        if (idade.compareTo("") == 0) {
            txtRes.setText("Debe indicar a idade");
            return;
        }
        if (!Utilidades.eNumeroEnteiro(idade)) {
            this.txtRes.setText("A idade debe ter un valor numérico enteiro");
            return;
        }
        int idadeI = new Integer(idade).intValue();
        if (idadeI < 0 || idadeI > 130) // A comprobacion de idade.length e para evitar enteiros maiores que (2^31)-1 (Integer.MAX_VALUE)
        {
            txtRes.setText("A idade debe estar entre 0 e 130");
            return;
        }
        if (telefono.compareTo("") == 0) {
            txtRes.setText("Debe indicar o teléfono");
            return;
        }
        txtRes.setText("Formulario correcto");

    }//GEN-LAST:event_btnGardarActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyTyped
// TODO add your handling code here:
        if (!isLetra(evt)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNomeKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EjJTextField.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EjJTextField.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EjJTextField.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EjJTextField.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EjJTextField().setVisible(true);
            }
        });

    }

    private boolean isLetra(java.awt.event.KeyEvent evt) {
// Comprobar se a pulsacion de teclado pasada
// en evt é unha letra
        char caracter = evt.getKeyChar();
        if (((caracter < 'A' || caracter > 'z')
                && (caracter != 'á')
                && (caracter != 'é')
                && (caracter != 'í')
                && (caracter != 'ó')
                && (caracter != 'ú')
                && (caracter != 'Á')
                && (caracter != 'É')
                && (caracter != 'Í')
                && (caracter != 'Ó')
                && (caracter != 'Ú')
                && (caracter != 'ñ')
                && (caracter != 'Ñ')
                && (caracter != KeyEvent.VK_SPACE)
                && (caracter != KeyEvent.VK_BACK_SPACE))
                || (evt.isAltDown()
                || evt.isAltGraphDown()
                || evt.isControlDown()
                || evt.isMetaDown())) {
            return false;
        }
        return true;
    }

    private boolean isNumero(java.awt.event.KeyEvent evt) {
// Comprobar se a pulsacion de teclado pasada
// en evt é un número
        char caracter = evt.getKeyChar();
        if (((caracter < '0' || caracter > '9')
                && (caracter != KeyEvent.VK_BACK_SPACE))
                || (evt.isAltDown()
                || evt.isAltGraphDown()
                || evt.isControlDown()
                || evt.isMetaDown())) {
            return false;
        }
        return true;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGardar;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblRes;
    private javax.swing.JLabel lblTel;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRes;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
