/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JTable;

import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author usuario
 */
public class EjJTable extends javax.swing.JFrame {

    private DefaultTableModel modeloMobles;

    /**
     * Creates new form EjJTable
     */
    public EjJTable() {
        initComponents();
        /*if (tblMobles.getRowCount()==0) {
            scpMobles.setVisible(false);
        lblDispoñibilidade.setVisible(true);
        }*/
        scpMobles.setVisible(false);
        lblDispoñibilidade.setVisible(true);

        modeloMobles = (DefaultTableModel) tblMobles.getModel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panNovoMoble = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        btnEngadir = new javax.swing.JButton();
        lblCor = new javax.swing.JLabel();
        txtCor = new javax.swing.JTextField();
        lblMaterial = new javax.swing.JLabel();
        cmbMaterial = new javax.swing.JComboBox<>();
        lblAncho = new javax.swing.JLabel();
        txtAncho = new javax.swing.JTextField();
        lblCmAncho = new javax.swing.JLabel();
        lblAlto = new javax.swing.JLabel();
        txtAlto = new javax.swing.JTextField();
        lblCmAlto = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();
        txtFondo = new javax.swing.JTextField();
        lblCmFondo = new javax.swing.JLabel();
        panMoblesDispoñibles = new javax.swing.JPanel();
        scpMobles = new javax.swing.JScrollPane();
        tblMobles = new javax.swing.JTable();
        lblDispoñibilidade = new javax.swing.JLabel();
        btnInformeMobles = new javax.swing.JButton();
        btnEliminarMoble = new javax.swing.JButton();
        btnEliminarTodos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panNovoMoble.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Novo mobile"));

        lblNome.setText("Nome");

        btnEngadir.setText("Engadir");
        btnEngadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEngadirActionPerformed(evt);
            }
        });

        lblCor.setText("Cor");

        lblMaterial.setText("Material");

        cmbMaterial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carballo", "Cerdeira", "Faia", "Ferro", "Piñeiro", "Plástico" }));
        cmbMaterial.setSelectedIndex(-1);

        lblAncho.setText("Ancho");

        lblCmAncho.setText("(cm)");

        lblAlto.setText("Alto");

        lblCmAlto.setText("(cm)");

        lblFondo.setText("Fondo");

        lblCmFondo.setText("(cm)");

        javax.swing.GroupLayout panNovoMobleLayout = new javax.swing.GroupLayout(panNovoMoble);
        panNovoMoble.setLayout(panNovoMobleLayout);
        panNovoMobleLayout.setHorizontalGroup(
            panNovoMobleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panNovoMobleLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panNovoMobleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panNovoMobleLayout.createSequentialGroup()
                        .addComponent(lblAncho)
                        .addGap(18, 18, 18)
                        .addComponent(txtAncho, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCmAncho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAlto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAlto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCmAlto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFondo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCmFondo)
                        .addGap(0, 137, Short.MAX_VALUE))
                    .addGroup(panNovoMobleLayout.createSequentialGroup()
                        .addGroup(panNovoMobleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome)
                            .addComponent(lblCor))
                        .addGap(18, 18, 18)
                        .addGroup(panNovoMobleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panNovoMobleLayout.createSequentialGroup()
                                .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblMaterial)
                                .addGap(18, 18, 18)
                                .addComponent(cmbMaterial, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEngadir, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panNovoMobleLayout.setVerticalGroup(
            panNovoMobleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panNovoMobleLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(panNovoMobleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEngadir))
                .addGap(7, 7, 7)
                .addGroup(panNovoMobleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCor)
                    .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaterial)
                    .addComponent(cmbMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panNovoMobleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAncho)
                    .addComponent(txtAncho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCmAncho)
                    .addComponent(lblAlto)
                    .addComponent(txtAlto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCmAlto)
                    .addComponent(lblFondo)
                    .addComponent(txtFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCmFondo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panMoblesDispoñibles.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Mobiles dispoñibles"));

        tblMobles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOME", "COR", "MATERIAL", "MEDIDAS (ANxAxF)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scpMobles.setViewportView(tblMobles);

        lblDispoñibilidade.setText("NON HAY MOBLES DISPOÑIBLES");

        btnInformeMobles.setText("Informe dos mobles");
        btnInformeMobles.setEnabled(false);
        btnInformeMobles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformeMoblesActionPerformed(evt);
            }
        });

        btnEliminarMoble.setText("Eliminar moble");
        btnEliminarMoble.setEnabled(false);
        btnEliminarMoble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMobleActionPerformed(evt);
            }
        });

        btnEliminarTodos.setText("Elininar todos");
        btnEliminarTodos.setEnabled(false);
        btnEliminarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panMoblesDispoñiblesLayout = new javax.swing.GroupLayout(panMoblesDispoñibles);
        panMoblesDispoñibles.setLayout(panMoblesDispoñiblesLayout);
        panMoblesDispoñiblesLayout.setHorizontalGroup(
            panMoblesDispoñiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMoblesDispoñiblesLayout.createSequentialGroup()
                .addGroup(panMoblesDispoñiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panMoblesDispoñiblesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnInformeMobles, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarMoble, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panMoblesDispoñiblesLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(lblDispoñibilidade)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panMoblesDispoñiblesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scpMobles, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panMoblesDispoñiblesLayout.setVerticalGroup(
            panMoblesDispoñiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMoblesDispoñiblesLayout.createSequentialGroup()
                .addComponent(lblDispoñibilidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpMobles, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panMoblesDispoñiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInformeMobles)
                    .addComponent(btnEliminarMoble)
                    .addComponent(btnEliminarTodos)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panNovoMoble, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panMoblesDispoñibles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(panNovoMoble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panMoblesDispoñibles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInformeMoblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformeMoblesActionPerformed
        // TODO add your handling code here:

        // Comprobar se hai mobles na taboa
        if (modeloMobles.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Non hai mobles dispoñibles");
            return;
        }

        //Comprobar se seleccionamos algun moble
        if (tblMobles.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar ao menos un moble");
            return;
        }

        //Recuperar os mobles do modelo
        int posicionesMobles[] = tblMobles.getSelectedRows();

        String resultado = "";
        for (int i = 0; i < posicionesMobles.length; i++) {
            Moble moble = (Moble) modeloMobles.getValueAt(posicionesMobles[i], 0);
            resultado += "Nome: " + moble.getNome() + " Cor: " + moble.getCor()
                    + " Material: " + moble.getMaterial() + " Ancho: " + moble.getAncho()
                    + " Alto: " + moble.getAlto() + " Fondo: " + moble.getFondo() + "\n";
        }

        JOptionPane.showMessageDialog(this, resultado);
    }//GEN-LAST:event_btnInformeMoblesActionPerformed

    private void btnEliminarMobleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMobleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarMobleActionPerformed

    private void btnEliminarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTodosActionPerformed
        // TODO add your handling code here:
        tblMobles.clearSelection();
    }//GEN-LAST:event_btnEliminarTodosActionPerformed

    private void btnEngadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEngadirActionPerformed
        // TODO add your handling code here:
        try {
            if (!(txtNome.getText().isBlank() && txtCor.getText().isBlank() && cmbMaterial.getSelectedIndex() == -1)) {
                Moble moble = new Moble(txtNome.getText(), txtCor.getText(), cmbMaterial.getSelectedItem().toString(),
                        Integer.parseInt(txtAncho.getText()), Integer.parseInt(txtFondo.getText()), Integer.parseInt(txtFondo.getText()));
                
                    //Engadir o moble á táboa
                    modeloMobles.setRowCount(modeloMobles.getRowCount() + 1);
                    modeloMobles.setValueAt(moble, modeloMobles.getRowCount() - 1, 0);
                    modeloMobles.setValueAt(moble.getCor(), modeloMobles.getRowCount() - 1, 1);
                    modeloMobles.setValueAt(moble.getMaterial(), modeloMobles.getRowCount() - 1, 2);
                    String medidas = moble.getAncho() + "x" + moble.getAlto() + "x" + moble.getFondo();
                    modeloMobles.setValueAt(medidas, modeloMobles.getRowCount() - 1, 3);
                    scpMobles.setVisible(true);
                    lblDispoñibilidade.setVisible(false);
                    btnInformeMobles.setEnabled(true);
                    btnEliminarMoble.setEnabled(true);
                    btnEliminarTodos.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this, "Parametros incorrectos. No se ha añadido la alfombra.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "El alto y el ancho tienen que ser enteros", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEngadirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EjJTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EjJTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EjJTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EjJTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EjJTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarMoble;
    private javax.swing.JButton btnEliminarTodos;
    private javax.swing.JButton btnEngadir;
    private javax.swing.JButton btnInformeMobles;
    private javax.swing.JComboBox<String> cmbMaterial;
    private javax.swing.JLabel lblAlto;
    private javax.swing.JLabel lblAncho;
    private javax.swing.JLabel lblCmAlto;
    private javax.swing.JLabel lblCmAncho;
    private javax.swing.JLabel lblCmFondo;
    private javax.swing.JLabel lblCor;
    private javax.swing.JLabel lblDispoñibilidade;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblMaterial;
    private javax.swing.JLabel lblNome;
    private javax.swing.JPanel panMoblesDispoñibles;
    private javax.swing.JPanel panNovoMoble;
    private javax.swing.JScrollPane scpMobles;
    private javax.swing.JTable tblMobles;
    private javax.swing.JTextField txtAlto;
    private javax.swing.JTextField txtAncho;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtFondo;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
