/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JRadioButton;

import java.awt.Color;
import java.awt.event.ItemEvent;

/**
 *
 * @author usuario
 */
public class Ej2JRadiobutton extends javax.swing.JFrame {

    /**
     * Creates new form Ej2JRadiobutton
     */
    public Ej2JRadiobutton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpCor = new javax.swing.ButtonGroup();
        lblElixeCor = new javax.swing.JLabel();
        panCor = new javax.swing.JPanel();
        rbtVermello = new javax.swing.JRadioButton();
        rbtVerde = new javax.swing.JRadioButton();
        rbtAzul = new javax.swing.JRadioButton();
        btnVermello = new javax.swing.JButton();
        btnVerde = new javax.swing.JButton();
        btnAzul = new javax.swing.JButton();
        lblCorSeleccionada = new javax.swing.JLabel();
        lblCor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblElixeCor.setText("Elixe unha cor entre as seleccionadas");

        panCor.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Cor"));

        btnGrpCor.add(rbtVermello);
        rbtVermello.setText("Vermello");
        rbtVermello.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtVermelloItemStateChanged(evt);
            }
        });

        btnGrpCor.add(rbtVerde);
        rbtVerde.setText("Verde");
        rbtVerde.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtVerdeItemStateChanged(evt);
            }
        });

        btnGrpCor.add(rbtAzul);
        rbtAzul.setText("Azul");
        rbtAzul.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtAzulItemStateChanged(evt);
            }
        });
        rbtAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtAzulActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panCorLayout = new javax.swing.GroupLayout(panCor);
        panCor.setLayout(panCorLayout);
        panCorLayout.setHorizontalGroup(
            panCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtVermello)
                    .addComponent(rbtVerde)
                    .addComponent(rbtAzul))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        panCorLayout.setVerticalGroup(
            panCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCorLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(rbtVermello)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtVerde)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtAzul)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnVermello.setText("Vermello");
        btnVermello.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVermelloActionPerformed(evt);
            }
        });

        btnVerde.setText("Verde");
        btnVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerdeActionPerformed(evt);
            }
        });

        btnAzul.setText("Azul");
        btnAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAzulActionPerformed(evt);
            }
        });

        lblCorSeleccionada.setText("Cor seleccionada");

        lblCor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblElixeCor)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(panCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnVermello, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVerde, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAzul, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblCorSeleccionada)
                                .addGap(57, 57, 57))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblCor, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblElixeCor)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(panCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVermello)
                            .addComponent(lblCorSeleccionada))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnVerde)
                            .addComponent(lblCor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnAzul)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVermelloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVermelloActionPerformed
        // TODO add your handling code here:
        rbtVermello.setSelected(true);
    }//GEN-LAST:event_btnVermelloActionPerformed

    private void rbtVermelloItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtVermelloItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            lblCor.setBackground(Color.red);
            lblCor.setText("VERMELLO");
        }

    }//GEN-LAST:event_rbtVermelloItemStateChanged

    private void rbtVerdeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtVerdeItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            lblCor.setBackground(Color.green);
            lblCor.setText("VERDE");
        }
    }//GEN-LAST:event_rbtVerdeItemStateChanged

    private void rbtAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtAzulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtAzulActionPerformed

    private void rbtAzulItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtAzulItemStateChanged
        // TODO add your handling code here:
         if (evt.getStateChange() == ItemEvent.SELECTED) {
            lblCor.setBackground(Color.BLUE);
            lblCor.setText("AZUL");
        }
    }//GEN-LAST:event_rbtAzulItemStateChanged

    private void btnVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerdeActionPerformed
        // TODO add your handling code here:
        rbtVerde.setSelected(true);
    }//GEN-LAST:event_btnVerdeActionPerformed

    private void btnAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAzulActionPerformed
        // TODO add your handling code here:
        rbtAzul.setSelected(true);
    }//GEN-LAST:event_btnAzulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ej2JRadiobutton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ej2JRadiobutton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ej2JRadiobutton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ej2JRadiobutton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ej2JRadiobutton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAzul;
    private javax.swing.ButtonGroup btnGrpCor;
    private javax.swing.JButton btnVerde;
    private javax.swing.JButton btnVermello;
    private javax.swing.JLabel lblCor;
    private javax.swing.JLabel lblCorSeleccionada;
    private javax.swing.JLabel lblElixeCor;
    private javax.swing.JPanel panCor;
    private javax.swing.JRadioButton rbtAzul;
    private javax.swing.JRadioButton rbtVerde;
    private javax.swing.JRadioButton rbtVermello;
    // End of variables declaration//GEN-END:variables
}
