/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JList;

/**
 *
 * @author usuario
 */
public class Ej2JList extends javax.swing.JFrame {

    /**
     * Creates new form Ej2JList
     */
    public Ej2JList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panCoresDispoñibles = new javax.swing.JPanel();
        scpCores = new javax.swing.JScrollPane();
        lstCores = new javax.swing.JList<>();
        lblSeleccionActual = new javax.swing.JLabel();
        lblCor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panCoresDispoñibles.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Cores dispoñibles"));

        lstCores.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Amarelo", "Azul", "Branco", "Gris", "Laranxa", "Marrón", "Morado", "Negro", "Ouro", "Prata", "Rosa", "Turquesa", "Violeta", "Vermello", "Verde", "Pistacho" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstCores.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCoresValueChanged(evt);
            }
        });
        scpCores.setViewportView(lstCores);

        lblSeleccionActual.setText("Seleccion actual");

        lblCor.setText("NINGUNHA");

        javax.swing.GroupLayout panCoresDispoñiblesLayout = new javax.swing.GroupLayout(panCoresDispoñibles);
        panCoresDispoñibles.setLayout(panCoresDispoñiblesLayout);
        panCoresDispoñiblesLayout.setHorizontalGroup(
            panCoresDispoñiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCoresDispoñiblesLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(scpCores, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(panCoresDispoñiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCoresDispoñiblesLayout.createSequentialGroup()
                        .addComponent(lblSeleccionActual)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCoresDispoñiblesLayout.createSequentialGroup()
                        .addComponent(lblCor)
                        .addGap(70, 70, 70))))
        );
        panCoresDispoñiblesLayout.setVerticalGroup(
            panCoresDispoñiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCoresDispoñiblesLayout.createSequentialGroup()
                .addGroup(panCoresDispoñiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCoresDispoñiblesLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(scpCores, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panCoresDispoñiblesLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblSeleccionActual)
                        .addGap(47, 47, 47)
                        .addComponent(lblCor)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panCoresDispoñibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panCoresDispoñibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstCoresValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCoresValueChanged
        // TODO add your handling code here:

        if (!evt.getValueIsAdjusting()) {
            String corSeleccionada = (String) lstCores.getModel().getElementAt(lstCores.getSelectedIndex());
            if (corSeleccionada.trim().compareTo("") == 0) {
                lblCor.setText("NINGUNHA");
            } else {
                lblCor.setText(corSeleccionada.toUpperCase());
            }
        }

    }//GEN-LAST:event_lstCoresValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ej2JList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ej2JList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ej2JList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ej2JList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ej2JList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCor;
    private javax.swing.JLabel lblSeleccionActual;
    private javax.swing.JList<String> lstCores;
    private javax.swing.JPanel panCoresDispoñibles;
    private javax.swing.JScrollPane scpCores;
    // End of variables declaration//GEN-END:variables
}
