/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tarefa6CompoñentesBasicos;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class CompoñentesBasicos extends javax.swing.JFrame {

    /**
     * Creates new form CompoñentesBasicos
     */
    public CompoñentesBasicos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtGrpDescontos = new javax.swing.ButtonGroup();
        rbtGrpCheckboxes = new javax.swing.ButtonGroup();
        panBotons = new javax.swing.JPanel();
        btnNovoCalculo = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        panPrincipal = new javax.swing.JPanel();
        panIzq = new javax.swing.JPanel();
        lblPeza = new javax.swing.JLabel();
        lblPrezoUnidade = new javax.swing.JLabel();
        txtPeza = new javax.swing.JTextField();
        txtPrezoUnidade = new javax.swing.JTextField();
        panUnidadesAdq = new javax.swing.JPanel();
        rbt1_10 = new javax.swing.JRadioButton();
        rbt11_50 = new javax.swing.JRadioButton();
        rbt50 = new javax.swing.JRadioButton();
        panDescontosAdicionais = new javax.swing.JPanel();
        chkEmpregado = new javax.swing.JCheckBox();
        chkClientePr = new javax.swing.JCheckBox();
        panDer = new javax.swing.JPanel();
        panResultado = new javax.swing.JPanel();
        scpResultado = new javax.swing.JScrollPane();
        txtarResultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Compoñentes Basicos");

        btnNovoCalculo.setText("Novo Calculo");
        btnNovoCalculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoCalculoActionPerformed(evt);
            }
        });

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panBotonsLayout = new javax.swing.GroupLayout(panBotons);
        panBotons.setLayout(panBotonsLayout);
        panBotonsLayout.setHorizontalGroup(
            panBotonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBotonsLayout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(btnNovoCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(234, Short.MAX_VALUE))
        );
        panBotonsLayout.setVerticalGroup(
            panBotonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBotonsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panBotonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoCalculo)
                    .addComponent(btnCalcular))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(panBotons, java.awt.BorderLayout.PAGE_END);

        lblPeza.setText("Peza");

        lblPrezoUnidade.setText("Prezo/Unidade");

        txtPeza.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPezaKeyTyped(evt);
            }
        });

        txtPrezoUnidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrezoUnidadeKeyTyped(evt);
            }
        });

        panUnidadesAdq.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Unidades Adquiridas"));

        rbtGrpDescontos.add(rbt1_10);
        rbt1_10.setText("1 - 10");

        rbtGrpDescontos.add(rbt11_50);
        rbt11_50.setText("11 - 50 (Desconto 5%)");

        rbtGrpDescontos.add(rbt50);
        rbt50.setText("> 50 (Desconto 15%)");

        javax.swing.GroupLayout panUnidadesAdqLayout = new javax.swing.GroupLayout(panUnidadesAdq);
        panUnidadesAdq.setLayout(panUnidadesAdqLayout);
        panUnidadesAdqLayout.setHorizontalGroup(
            panUnidadesAdqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panUnidadesAdqLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(panUnidadesAdqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbt50)
                    .addComponent(rbt11_50)
                    .addComponent(rbt1_10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panUnidadesAdqLayout.setVerticalGroup(
            panUnidadesAdqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panUnidadesAdqLayout.createSequentialGroup()
                .addComponent(rbt1_10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbt11_50)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(rbt50))
        );

        panDescontosAdicionais.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Discontos Adicionais"), "Descontos Adicionais"));

        rbtGrpCheckboxes.add(chkEmpregado);
        chkEmpregado.setText("Empregado (Desconto 10%)");

        rbtGrpCheckboxes.add(chkClientePr);
        chkClientePr.setText("Cliente Premium (Desconto 5%)");

        javax.swing.GroupLayout panDescontosAdicionaisLayout = new javax.swing.GroupLayout(panDescontosAdicionais);
        panDescontosAdicionais.setLayout(panDescontosAdicionaisLayout);
        panDescontosAdicionaisLayout.setHorizontalGroup(
            panDescontosAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDescontosAdicionaisLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panDescontosAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkClientePr)
                    .addComponent(chkEmpregado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panDescontosAdicionaisLayout.setVerticalGroup(
            panDescontosAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panDescontosAdicionaisLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(chkEmpregado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkClientePr)
                .addContainerGap())
        );

        javax.swing.GroupLayout panIzqLayout = new javax.swing.GroupLayout(panIzq);
        panIzq.setLayout(panIzqLayout);
        panIzqLayout.setHorizontalGroup(
            panIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panIzqLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(panIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panUnidadesAdq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panIzqLayout.createSequentialGroup()
                        .addGroup(panIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPeza)
                            .addComponent(lblPrezoUnidade))
                        .addGap(25, 25, 25)
                        .addGroup(panIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPeza, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrezoUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 24, Short.MAX_VALUE))
                    .addComponent(panDescontosAdicionais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panIzqLayout.setVerticalGroup(
            panIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panIzqLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(panIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeza)
                    .addComponent(txtPeza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrezoUnidade)
                    .addComponent(txtPrezoUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panUnidadesAdq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panDescontosAdicionais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        panResultado.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Resultado do calculo"));

        txtarResultado.setBackground(new java.awt.Color(255, 255, 102));
        txtarResultado.setColumns(20);
        txtarResultado.setRows(5);
        scpResultado.setViewportView(txtarResultado);

        javax.swing.GroupLayout panResultadoLayout = new javax.swing.GroupLayout(panResultado);
        panResultado.setLayout(panResultadoLayout);
        panResultadoLayout.setHorizontalGroup(
            panResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scpResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addContainerGap())
        );
        panResultadoLayout.setVerticalGroup(
            panResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panResultadoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(scpResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panDerLayout = new javax.swing.GroupLayout(panDer);
        panDer.setLayout(panDerLayout);
        panDerLayout.setHorizontalGroup(
            panDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );
        panDerLayout.setVerticalGroup(
            panDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panPrincipalLayout = new javax.swing.GroupLayout(panPrincipal);
        panPrincipal.setLayout(panPrincipalLayout);
        panPrincipalLayout.setHorizontalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addComponent(panIzq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panDer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panPrincipalLayout.setVerticalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPrincipalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panIzq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panDer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(panPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPezaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPezaKeyTyped
        // TODO add your handling code here:
        if (!isLetra(evt)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPezaKeyTyped

    private void txtPrezoUnidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrezoUnidadeKeyTyped
        // TODO add your handling code here:
        if (!isNumero(evt) || txtPrezoUnidade.getText().length() >= 7) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPrezoUnidadeKeyTyped

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        String peza = txtPeza.getText().trim();
        String prezo = txtPrezoUnidade.getText().trim();

        if (peza.equals("")) {
            JOptionPane.showMessageDialog(this, "El nombre de la pieza es obligatorio.");
        } else if (prezo.equals("")) {
            JOptionPane.showMessageDialog(this, "El precio es obligatorio.");
        } else {
            txtarResultado.setText(txtarResultado.getText() + "\nPeza: " + peza);
            txtarResultado.setText(txtarResultado.getText() + "\nPrezo / unidade sen desconto: " + prezo);

            int precioIni = Integer.parseInt(prezo);
            int precio = precioIni;
            precio = aplicaDescontos(precio);

            if (precioIni == precio) {
                txtarResultado.setText(txtarResultado.getText() + "\n\nNon hay descontos aplicables sobre o precio final");
            } else {

                txtarResultado.setText(txtarResultado.getText() + "\n\nDescontos aplicados: ");
                txtarResultado.setText(txtarResultado.getText() + "\n-------------------");
                int descontoTotal = comprobaDescontos();
                txtarResultado.setText(txtarResultado.getText() + "\nDesconto total sobre o prezo final: " + descontoTotal + " %");
                txtarResultado.setText(txtarResultado.getText() + "\nPrezo con desconto: " + precio);
            }

        }


    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnNovoCalculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoCalculoActionPerformed
        // TODO add your handling code here:

        txtPeza.setText("");
        txtPrezoUnidade.setText("");
        txtarResultado.setText("");
        
        rbtGrpDescontos.clearSelection();
        rbtGrpCheckboxes.clearSelection();
    }//GEN-LAST:event_btnNovoCalculoActionPerformed

    public int aplicaDescontos(int precio) {
        if (rbt11_50.isSelected()) {
            precio -= (int) (precio * 0.05);
        } else if (rbt50.isSelected()) {
            precio -= (int) (precio * 0.15);
        }

        if (chkEmpregado.isSelected()) {
            precio -= (int) (precio * 0.1);
        }

        if (chkClientePr.isSelected()) {
            precio -= (int) (precio * 0.05);
        }

        return precio;
    }

    public int comprobaDescontos() {
        int desconto = 0;
        if (rbt11_50.isSelected()) {
            txtarResultado.setText(txtarResultado.getText() + "\nDesconto por unidades adquiridas: 5%");
            desconto += 5;
        } else if (rbt50.isSelected()) {
            txtarResultado.setText(txtarResultado.getText() + "\nDesconto por unidades adquiridas: 10%");
            desconto += 10;
        }

        if (chkEmpregado.isSelected()) {
            txtarResultado.setText(txtarResultado.getText() + "\nDesconto por unidades adquiridas: 5%");
            desconto += 5;
        } else if (chkClientePr.isSelected()) {
            txtarResultado.setText(txtarResultado.getText() + "\nDesconto por unidades adquiridas: 10%");
            desconto += 10;
        }

        return desconto;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompoñentesBasicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompoñentesBasicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompoñentesBasicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompoñentesBasicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompoñentesBasicos().setVisible(true);
            }
        });
    }

    private boolean isLetra(java.awt.event.KeyEvent evt) {
        // Comprobar se a pulsacion de teclado pasada
        // en evt é unha letra
        char caracter = evt.getKeyChar();
        if (((caracter < 'A' || caracter > 'z')
                && (caracter != 'á')
                && (caracter != 'é')
                && (caracter != 'í')
                && (caracter != 'ó')
                && (caracter != 'ú')
                && (caracter != 'Á')
                && (caracter != 'É')
                && (caracter != 'Í')
                && (caracter != 'Ó')
                && (caracter != 'Ú')
                && (caracter != 'ñ')
                && (caracter != 'Ñ')
                && (caracter != KeyEvent.VK_SPACE)
                && (caracter != KeyEvent.VK_BACK_SPACE))
                || (evt.isAltDown()
                || evt.isAltGraphDown()
                || evt.isControlDown()
                || evt.isMetaDown())) {
            return false;
        }
        return true;
    }

    private boolean isNumero(java.awt.event.KeyEvent evt) {
        // Comprobar se a pulsacion de teclado pasada
        // en evt é un número
        char caracter = evt.getKeyChar();
        if (((caracter < '0' || caracter > '9')
                && (caracter != KeyEvent.VK_BACK_SPACE))
                || (evt.isAltDown()
                || evt.isAltGraphDown()
                || evt.isControlDown()
                || evt.isMetaDown())) {
            return false;
        }
        return true;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnNovoCalculo;
    private javax.swing.JCheckBox chkClientePr;
    private javax.swing.JCheckBox chkEmpregado;
    private javax.swing.JLabel lblPeza;
    private javax.swing.JLabel lblPrezoUnidade;
    private javax.swing.JPanel panBotons;
    private javax.swing.JPanel panDer;
    private javax.swing.JPanel panDescontosAdicionais;
    private javax.swing.JPanel panIzq;
    private javax.swing.JPanel panPrincipal;
    private javax.swing.JPanel panResultado;
    private javax.swing.JPanel panUnidadesAdq;
    private javax.swing.JRadioButton rbt11_50;
    private javax.swing.JRadioButton rbt1_10;
    private javax.swing.JRadioButton rbt50;
    private javax.swing.ButtonGroup rbtGrpCheckboxes;
    private javax.swing.ButtonGroup rbtGrpDescontos;
    private javax.swing.JScrollPane scpResultado;
    private javax.swing.JTextField txtPeza;
    private javax.swing.JTextField txtPrezoUnidade;
    private javax.swing.JTextArea txtarResultado;
    // End of variables declaration//GEN-END:variables
}
