/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JComboBox;

import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author usuario
 */
public class Ej2JCombobox extends javax.swing.JFrame {

    /**
     * Creates new form Ej2JCombobox
     */
    
    private javax.swing.DefaultComboBoxModel modeloConcellos;
    
    public Ej2JCombobox() {
        initComponents();
        //crear o modelo para almacenar as alfombras
        modeloConcellos = new DefaultComboBoxModel();
        //ligar o modelo ao control JComboBox
        cmbConcello.setModel(modeloConcellos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProvincia = new javax.swing.JLabel();
        lblConcello = new javax.swing.JLabel();
        cmbProvincia = new javax.swing.JComboBox<>();
        cmbConcello = new javax.swing.JComboBox<>();
        lblConcelloSeleccionado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblProvincia.setText("Provincia");

        lblConcello.setText("Concello");

        cmbProvincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A Coruña", "Lugo", "Pontevedra", "Ourense" }));
        cmbProvincia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbProvinciaItemStateChanged(evt);
            }
        });

        cmbConcello.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbConcello.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbConcelloItemStateChanged(evt);
            }
        });

        lblConcelloSeleccionado.setText("Concelo seleccionado: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProvincia)
                            .addComponent(lblConcello))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbConcello, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(lblConcelloSeleccionado)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProvincia)
                    .addComponent(cmbProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConcello)
                    .addComponent(cmbConcello, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(lblConcelloSeleccionado)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbProvinciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbProvinciaItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            int posicionProvincia = cmbProvincia.getSelectedIndex();
            cargarConcellos(posicionProvincia);
        }
    }//GEN-LAST:event_cmbProvinciaItemStateChanged

    private void cmbConcelloItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbConcelloItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            lblConcelloSeleccionado.setText("Concello seleccionado: "
                    + modeloConcellos.getElementAt(cmbConcello.getSelectedIndex()).toString().toUpperCase());
        }
    }//GEN-LAST:event_cmbConcelloItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ej2JCombobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ej2JCombobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ej2JCombobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ej2JCombobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ej2JCombobox().setVisible(true);
            }
        });
    }

    private void cargarConcellos(int codProvincia) {
        modeloConcellos.removeAllElements();
        switch (codProvincia) {
            case 0:
                for (int i = 0; i < concellosCorunha.length; i++) {
                    modeloConcellos.addElement(concellosCorunha[i]);
                }
                break;
            case 1:
                for (int i = 0; i < concellosLugo.length; i++) {
                    modeloConcellos.addElement(concellosLugo[i]);
                }
                break;
            case 2:
                for (int i = 0; i < concellosPontevedra.length; i++) {
                    modeloConcellos.addElement(concellosPontevedra[i]);
                }
                break;
            case 3:
                for (int i = 0; i < concellosOurense.length; i++) {
                    modeloConcellos.addElement(concellosOurense[i]);
                }
                break;
        }
    }

    //Pequena "base de datos" de concellos por provincias
    private String[] concellosCorunha = {"Betanzos", "Ferrol", "Pontedeume"};
    private String[] concellosLugo = {"Foz", "Quiroga", "Triacastela"};
    private String[] concellosOurense = {"Bande", "Castro Caldelas", "Maside"};
    private String[] concellosPontevedra = {"Cangas", "Bueu", "Marín", "Pontevedra", "Tomiño"};

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbConcello;
    private javax.swing.JComboBox<String> cmbProvincia;
    private javax.swing.JLabel lblConcello;
    private javax.swing.JLabel lblConcelloSeleccionado;
    private javax.swing.JLabel lblProvincia;
    // End of variables declaration//GEN-END:variables

}
