/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JComboBox;

import JTextField.LimiteLonxitudeJTextField;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class EjJComboBox extends javax.swing.JFrame {

    /**
     * Creates new form EjJComboBox
     */
    private javax.swing.DefaultComboBoxModel modeloAlfombras;

    public EjJComboBox() {
        initComponents();
        //crear o modelo para almacenar as alfombras
        modeloAlfombras = new DefaultComboBoxModel();
        //ligar o modelo ao control JComboBox
        cmbAlfombras.setModel(modeloAlfombras);
        txtAlto.setDocument(new LimiteLonxitudeJTextField(5));
        txtAncho.setDocument(new LimiteLonxitudeJTextField(5));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panNovaAlfombra = new javax.swing.JPanel();
        lblModelo = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        lblCor = new javax.swing.JLabel();
        txtCor = new javax.swing.JTextField();
        lblAncho = new javax.swing.JLabel();
        lblCm = new javax.swing.JLabel();
        txtAncho = new javax.swing.JTextField();
        lblAlto = new javax.swing.JLabel();
        txtAlto = new javax.swing.JTextField();
        lblCm2 = new javax.swing.JLabel();
        btnEngadir = new javax.swing.JButton();
        panAlfombrasDispoñibles = new javax.swing.JPanel();
        cmbAlfombras = new javax.swing.JComboBox<>();
        btnInfoAlfombra = new javax.swing.JButton();
        btnEliminarAlfombra = new javax.swing.JButton();
        btnEliminarTodas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panNovaAlfombra.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Nova alfombra"));

        lblModelo.setText("Modelo");

        lblCor.setText("Cor");

        lblAncho.setText("Ancho");

        lblCm.setText("(cm)");

        lblAlto.setText("Alto");

        lblCm2.setText("(cm)");

        btnEngadir.setText("Engadir");
        btnEngadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEngadirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panNovaAlfombraLayout = new javax.swing.GroupLayout(panNovaAlfombra);
        panNovaAlfombra.setLayout(panNovaAlfombraLayout);
        panNovaAlfombraLayout.setHorizontalGroup(
            panNovaAlfombraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panNovaAlfombraLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panNovaAlfombraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCor)
                    .addComponent(lblModelo))
                .addGap(41, 41, 41)
                .addGroup(panNovaAlfombraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panNovaAlfombraLayout.createSequentialGroup()
                        .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(btnEngadir, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panNovaAlfombraLayout.createSequentialGroup()
                        .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblAncho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAncho, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCm, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblAlto)
                        .addGap(18, 18, 18)
                        .addComponent(txtAlto, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCm2)))
                .addContainerGap())
        );
        panNovaAlfombraLayout.setVerticalGroup(
            panNovaAlfombraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panNovaAlfombraLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panNovaAlfombraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelo)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEngadir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(panNovaAlfombraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCor)
                    .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAncho)
                    .addComponent(lblCm)
                    .addComponent(txtAncho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAlto)
                    .addComponent(txtAlto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCm2))
                .addGap(20, 20, 20))
        );

        panAlfombrasDispoñibles.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Alfombras Dispoñibles")));

        btnInfoAlfombra.setText("Informacion de la Alfombra");
        btnInfoAlfombra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoAlfombraActionPerformed(evt);
            }
        });

        btnEliminarAlfombra.setText("Eliminar Alfombra");
        btnEliminarAlfombra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAlfombraActionPerformed(evt);
            }
        });

        btnEliminarTodas.setText("Eliminar todas");
        btnEliminarTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTodasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panAlfombrasDispoñiblesLayout = new javax.swing.GroupLayout(panAlfombrasDispoñibles);
        panAlfombrasDispoñibles.setLayout(panAlfombrasDispoñiblesLayout);
        panAlfombrasDispoñiblesLayout.setHorizontalGroup(
            panAlfombrasDispoñiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panAlfombrasDispoñiblesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panAlfombrasDispoñiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbAlfombras, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panAlfombrasDispoñiblesLayout.createSequentialGroup()
                        .addComponent(btnInfoAlfombra, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarAlfombra, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarTodas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panAlfombrasDispoñiblesLayout.setVerticalGroup(
            panAlfombrasDispoñiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAlfombrasDispoñiblesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(cmbAlfombras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panAlfombrasDispoñiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInfoAlfombra)
                    .addComponent(btnEliminarAlfombra)
                    .addComponent(btnEliminarTodas))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panNovaAlfombra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panAlfombrasDispoñibles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(panNovaAlfombra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panAlfombrasDispoñibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEngadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEngadirActionPerformed
        // TODO add your handling code here:
        try {
            if (!(txtModelo.getText().isBlank() && txtCor.getText().isBlank())) {
                Alfombra a = new Alfombra(txtModelo.getText(), txtCor.getText(), Integer.parseInt(txtAncho.getText()), Integer.parseInt(txtAlto.getText()));
                modeloAlfombras.addElement(a);
            }else{
                 JOptionPane.showMessageDialog(this, "Parametros incorrectos. No se ha añadido la alfombra.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "El alto y el ancho tienen que ser enteros", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEngadirActionPerformed

    private void btnInfoAlfombraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoAlfombraActionPerformed
        // TODO add your handling code here:
        // Comprobar se hai alfombras no combo
        if (modeloAlfombras.getSize() == 0) {
            JOptionPane.showMessageDialog(this, "Non hai alfombras dispoñibles");
            return;
        }

        //Comprobar se seleccionamos algunha alfombra
        if (cmbAlfombras.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar ao menos unha alfombra");
            return;
        }

        //Recuperar a alfombra do modelo
        Alfombra alfombra = (Alfombra) modeloAlfombras.getElementAt(cmbAlfombras.getSelectedIndex());
        //Mostras información das alfombra por pantalla
        JOptionPane.showMessageDialog(this, "MODELO: " + alfombra.getModelo() + "\nCOR: "
                + alfombra.getCor() + "\nANCHO: " + alfombra.getAncho() + " cm\nALTO: " + alfombra.getAlto() +"cm"); 
    }//GEN-LAST:event_btnInfoAlfombraActionPerformed

    private void btnEliminarAlfombraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAlfombraActionPerformed
        // TODO add your handling code here:
        modeloAlfombras.removeElementAt(cmbAlfombras.getSelectedIndex());
    }//GEN-LAST:event_btnEliminarAlfombraActionPerformed

    private void btnEliminarTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTodasActionPerformed
        // TODO add your handling code here:
        modeloAlfombras.removeAllElements();
    }//GEN-LAST:event_btnEliminarTodasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EjJComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EjJComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EjJComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EjJComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EjJComboBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarAlfombra;
    private javax.swing.JButton btnEliminarTodas;
    private javax.swing.JButton btnEngadir;
    private javax.swing.JButton btnInfoAlfombra;
    private javax.swing.JComboBox<Alfombra> cmbAlfombras;
    private javax.swing.JLabel lblAlto;
    private javax.swing.JLabel lblAncho;
    private javax.swing.JLabel lblCm;
    private javax.swing.JLabel lblCm2;
    private javax.swing.JLabel lblCor;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JPanel panAlfombrasDispoñibles;
    private javax.swing.JPanel panNovaAlfombra;
    private javax.swing.JTextField txtAlto;
    private javax.swing.JTextField txtAncho;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtModelo;
    // End of variables declaration//GEN-END:variables
}
